version: "2"

services:
  s3-data:
    container_name: s3-data
    build:
      context: .
    image: ayecaptn/s3-data:latest
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - S3_BUCKET
    volumes:
      - ./data:/mnt/s3
      - s3_data:/mnt/s3

volumes:
  s3_data